declare const classNames: {
  readonly container: "container";
  readonly fullWidth: "fullWidth";
  readonly label: "label";
  readonly required: "required";
  readonly error: "error";
  readonly helper: "helper";
  readonly positioner: "positioner";
  readonly popup: "popup";
  readonly list: "list";
  readonly item: "item";
  readonly itemText: "itemText";
  readonly itemIndicator: "itemIndicator";
  readonly stateRow: "stateRow";
  readonly emptyText: "emptyText";
  readonly triggerError: "triggerError";
  readonly trigger: "trigger";
  readonly chevron: "chevron";
  readonly placeholder: "placeholder";
  readonly value: "value";
  readonly triggerPrefix: "triggerPrefix";
  readonly itemPrefix: "itemPrefix";
  readonly itemSuffix: "itemSuffix";
  readonly searchWrapper: "searchWrapper";
  readonly input: "input";
};
export = classNames;
