declare const classNames: {
  readonly container: "container";
  readonly info: "info";
  readonly warning: "warning";
  readonly success: "success";
  readonly error: "error";
  readonly neutral: "neutral";
  readonly header: "header";
  readonly iconContainer: "iconContainer";
  readonly infoIcon: "infoIcon";
  readonly warningIcon: "warningIcon";
  readonly successIcon: "successIcon";
  readonly errorIcon: "errorIcon";
  readonly neutralIcon: "neutralIcon";
  readonly title: "title";
  readonly descriptionWrapper: "descriptionWrapper";
  readonly descriptionWrapperWithAction: "descriptionWrapperWithAction";
  readonly description: "description";
  readonly footer: "footer";
};
export = classNames;
