declare const classNames: {
  readonly container: "container";
  readonly header: "header";
  readonly headerDay: "headerDay";
  readonly body: "body";
  readonly week: "week";
  readonly dayCell: "dayCell";
  readonly selected: "selected";
  readonly dayNumber: "dayNumber";
  readonly today: "today";
  readonly hours: "hours";
  readonly otherMonth: "otherMonth";
  readonly statusFull: "statusFull";
  readonly statusHalf: "statusHalf";
  readonly statusLate: "statusLate";
  readonly statusAbsent: "statusAbsent";
  readonly statusWeekend: "statusWeekend";
  readonly stateOverlay: "stateOverlay";
  readonly footer: "footer";
};
export = classNames;
