declare const classNames: {
  readonly fieldInput: "fieldInput";
  readonly fieldBooleanContainer: "fieldBooleanContainer";
  readonly fieldBooleanReadonly: "fieldBooleanReadonly";
  readonly fieldSelectDropdown: "fieldSelectDropdown";
  readonly fieldWeekdayContainer: "fieldWeekdayContainer";
  readonly weekdayGroup: "weekdayGroup";
  readonly weekdayToggle: "weekdayToggle";
  readonly fieldTimeWrapper: "fieldTimeWrapper";
  readonly fieldTimeTrigger: "fieldTimeTrigger";
  readonly fieldTimeChevron: "fieldTimeChevron";
  readonly fieldTimePopover: "fieldTimePopover";
  readonly fieldTimeColumn: "fieldTimeColumn";
  readonly fieldTimeColumnLabel: "fieldTimeColumnLabel";
  readonly fieldTimeColumnList: "fieldTimeColumnList";
  readonly fieldTimeOption: "fieldTimeOption";
  readonly fieldTimeOptionActive: "fieldTimeOptionActive";
  readonly fieldTimeOptionDisabled: "fieldTimeOptionDisabled";
};
export = classNames;
