/*
 *  _   _                _
 * | |_(_)_ __ ___   ___| | _____  ___ _ __
 * | __| | '_ ` _ \ / _ \ |/ / _ \/ _ \ '_ \
 * | |_| | | | | | |  __/   <  __/  __/ |_) |
 *  \__|_|_| |_| |_|\___|_|\_\___|\___| .__/
 *                                    |_|
 *
 * timekeep - UI Component Library
 *
 * ⚠️  AUTO-GENERATED by scripts/generate-ui-barrel.ts
 *    Do not edit directly. Run `pnpm generate-ui-barrel` to regenerate.
 *
 * Barrel file. Every component exposes its public API via its own index.ts.
 * Import like: import { Button, Card } from "@/components/ui";
 */

// ── Core ──
export { ActionGroup } from "./action-group";
export { Avatar } from "./avatar";
export { Badge } from "./badge";
export { Banner } from "./banner";
export { Button } from "./button";
export type { ButtonProps } from "./button";
export { Card } from "./card";
export { CardGrid } from "./card-grid";
export { Chart, BarChart, LineChart, PieChart, buildNivoTheme, useChartTheme } from "./chart";
export type {
  ChartProps,
  BarDef,
  BarChartProps,
  LineDef,
  LineChartProps,
  SliceDef,
  PieChartProps,
  ChartTheme,
} from "./chart";
export { Checkbox } from "./checkbox";
export { ClickableListItem } from "./clickable-list-item";
export { Combobox } from "./combobox";
export type { ComboboxOption } from "./combobox";
export { DataTable, TextCell, TimestampCell, DurationCell, StatusCell } from "./data-table";
export type { SortDirection, SortState, DataTableColumn } from "./data-table";
export { DatePicker } from "./date-picker";
export type { DateRangePreset } from "./date-picker";
export { DetailGrid, DetailItem } from "./detail-grid";
export { Dialog } from "./dialog";
export { Dropdown, useDropdownContext } from "./dropdown";
export { DropdownContent } from "./dropdown-content";
export { DropdownSearch } from "./dropdown-search";
export { EllipsisDisplay } from "./ellipsis-display";
export type { EllipsisDisplayProps } from "./ellipsis-display";
export { EmptyState } from "./empty-state";
export { FilterBar } from "./filter-bar";
export type { ActiveFilter } from "./filter-bar";
export { FilterDateRange } from "./filter-date-range";
export { FilterDropdown } from "./filter-dropdown";
export type { FilterChip, FilterField } from "./filter-dropdown";
export { FilterInput } from "./filter-input";
export { FilterSelect } from "./filter-select";
export {
  Form,
  FormField,
  FormActions,
  FormSection,
  FormFieldInput,
  FieldInputContainer,
  SchemaForm,
} from "./form";
export type { FormFieldDef } from "./form";
export { Grid } from "./grid";
export { Heading } from "./heading";
export type { HeadingLevel, HeadingColor } from "./heading";
export { IconButton } from "./icon-button";
export { InfiniteScrollSentinel } from "./infinite-scroll-sentinel";
export { InlineHeader } from "./inline-header";
export { Input } from "./input";
export { LinkChip } from "./link-chip";
export type { LinkChipProps, TriggerEventType } from "./link-chip";
export { ListItem } from "./list-item";
export { MenuItem, MenuCloseContext } from "./menu-item";
export type { CloseDropdownFn } from "./menu-item";
export { MenuItemNavigate } from "./menu-item-navigate";
export { MenuSeparator } from "./menu-separator";
export { MetricCard } from "./metric-card";
export type { MetricCardColor } from "./metric-card";
export { MultiSelect } from "./multi-select";
export type { MultiSelectOption } from "./multi-select";
export { PageBar } from "./page-bar";
export type { BreadcrumbSegment } from "./page-bar";
export { PageBody } from "./page-body";
export { PageHeader } from "./page-header";
export { PageLayout } from "./page-layout";
export { Pagination } from "./pagination";
export { ProgressBar } from "./progress-bar";
export { SearchInput } from "./search-input";
export { Section } from "./section";
export { Select } from "./select";
export { Separator } from "./separator";
export { Skeleton, SkeletonLines } from "./skeleton";
export { Spinner } from "./spinner";
export { StatusDot } from "./status-dot";
export { TabList, Tab, TabPanel } from "./tab-list";
export { Text } from "./text";
export type { TextVariant, TextColor, TextElement } from "./text";
export { TextArea } from "./text-area";
export { Toggle } from "./toggle";
export { Tooltip } from "./tooltip";
export { VisuallyHidden } from "./visually-hidden";

// ── Phase 3+ molecules ──
export { Callout } from "./callout";
export type { CalloutProps, CalloutVariant } from "./callout";
export { PageError } from "./page-error";
export { DataBoundary } from "./data-boundary";
export { TintedIconTile } from "./tinted-icon-tile";
export type { TintedIconTileProps, TintedIconTileColor } from "./tinted-icon-tile";
export { AnimatedPlaceholder } from "./animated-placeholder";
export type { AnimatedPlaceholderProps, AnimatedPlaceholderType } from "./animated-placeholder";
export { Info } from "./info";
export type { InfoProps, InfoAccent } from "./info";
export { Tag } from "./tag";
export type { TagProps, TagColor, TagVariant, TagWeight } from "./tag";
export { AnimatedButton } from "./animated-button";
export type { AnimatedButtonProps } from "./animated-button";
export { OverflowingTextWithTooltip } from "./overflowing-text-with-tooltip";
export type { OverflowingTextWithTooltipProps } from "./overflowing-text-with-tooltip";
export { CircularProgressBar } from "./circular-progress-bar";
export type { CircularProgressBarProps } from "./circular-progress-bar";

// ── Device management molecules ──
export { StorageGauge } from "./storage-gauge";
export { Dot } from "./dot";
export { DeviceHealthCard } from "./device-health-card";
export { ActivityTimeline } from "./activity-timeline";
export { Timeline } from "./timeline";
export type { TimelineBlockData, TimelineRowData } from "./timeline";
export { AvatarGroup } from "./avatar-group";
export type { AvatarGroupProps } from "./avatar-group";
export { CalendarMonth } from "./calendar-month";
export type { CalendarMonthProps, CalendarDay } from "./calendar-month";
export { ViewBar } from "./view-bar";
export type { ViewBarProps, ViewType, ViewBarFilterChip, SortChip } from "./view-bar";

// ── Specialized form inputs ──
export { IpInput, isValidIpv4 } from "./ip-input";
export { PortInput, clampPort } from "./port-input";
export { IpPortInput, parseIpPort } from "./ip-port-input";
export { ExpiryPicker } from "./expiry-picker";
export type { ExpiryPreset, ExpiryValue } from "./expiry-picker";
export {
  PermissionMultiSelect,
  ALL_PERMISSIONS,
  getPermission,
  parsePermissionsString,
} from "./permission-multiselect";

// ── Right side panel ──
export { SidePanel, ResizablePanelGap } from "./side-panel";
