/*
 *  _   _                _
 * | |_(_)_ __ ___   ___| | _____  ___ _ __
 * | __| | '_ ` _ \ / _ \ |/ / _ \/ _ \ '_ \
 * | |_| | | | | | |  __/   <  __/  __/ |_) |
 *  \__|_|_| |_| |_|\___|_|\_\___|\___| .__/
 *                                    |_|
 *
 * timekeep - UI Component Library
 *
 * ⚠️  AUTO-GENERATED by scripts/generate-ui-barrel.ts
 *    Do not edit directly. Run `pnpm generate-ui-barrel` to regenerate.
 *
 * ── Hierarchy (see .notes/architecture/component-hierarchy.md) ──────────
 *
 *   TIER 1 — Primitives      │ Modules MUST NOT import directly
 *   TIER 2 — Widgets          │ Modules MAY import directly
 *   TIER 3 — Composites       │ @/modules/shared/components/
 *   TIER 4 — Layout Shell     │ @/components/layout/
 *   TIER 5 — Domain Modules   │ @/modules/{domain}/
 *
 * Import contracts:
 *   import { Section, Grid } from "@/components/ui";        // ✅ pages only
 *   import { DataTable, Form } from "@/components/ui";      // ✅ widgets
 *   import { DataBoundary } from "@/modules/shared/components"; // ✅ composites
 *   import { PageLayout } from "@/components/layout";        // ✅ layout
 *   import { Card, Text, Badge } from "@/components/ui";     // ❌ primitive in module
 */

// ── Tier 1: Primitives (atoms) — DO NOT import in modules ─────────────────
export { Avatar } from "./avatar";
export { Badge } from "./badge";
export { Banner } from "./banner";
export { Button } from "./button";
export type { ButtonProps } from "./button";
export { Card } from "./card";
export { Checkbox } from "./checkbox";
export { CircularProgressBar } from "./circular-progress-bar";
export type { CircularProgressBarProps } from "./circular-progress-bar";
export { Dot } from "./dot";
export { Heading } from "./heading";
export type { HeadingLevel, HeadingColor } from "./heading";
export { IconButton } from "./icon-button";
export { Input } from "./input";
export { MenuSeparator } from "./menu-separator";
export { ProgressBar } from "./progress-bar";
export { Separator } from "./separator";
export { Skeleton, SkeletonLines } from "./skeleton";
export { Spinner } from "./spinner";
export { StatusDot } from "./status-dot";
export { Switch } from "./switch";
export { Text } from "./text";
export type { TextVariant, TextColor, TextElement } from "./text";
export { TextArea } from "./text-area";
export { Tooltip } from "./tooltip";
export { VisuallyHidden } from "./visually-hidden";

// Display (read-only cell renderers)
export {
  EllipsisDisplay,
  TextDisplay,
  BooleanDisplay,
  DateDisplay,
  NumberDisplay,
  SelectDisplay,
  MultiSelectDisplay,
} from "./display";

// Field Input (inline editing primitives)
export {
  FieldTextInput,
  FieldBooleanInput,
  FieldDateInput,
  FieldSelectInput,
  FieldMultiSelectInput,
  FieldNumberInput,
  FieldTimeInput,
  FieldWeekdayToggle,
  isNonTextWritingKey,
} from "./field-input";

// Inline Field Edit (detail view click-to-edit)
export { InlineFieldEdit } from "./inline-field-edit";
export type { InlineFieldEditProps } from "./inline-field-edit";
export type {
  FieldTextInputProps,
  FieldBooleanInputProps,
  FieldDateInputProps,
  FieldSelectInputProps,
  FieldMultiSelectInputProps,
  FieldNumberInputProps,
  FieldTimeInputProps,
  FieldWeekdayToggleProps,
} from "./field-input";

// ── Tier 1: Primitives (simple molecules) — DO NOT import in modules ─────
export { ActionGroup } from "./action-group";
export { AvatarGroup } from "./avatar-group";
export type { AvatarGroupProps } from "./avatar-group";
export { Breadcrumb } from "./breadcrumb";
export type { BreadcrumbSegment } from "./breadcrumb";
export { ClickableListItem } from "./clickable-list-item";
export { ConfirmDialog } from "./confirm-dialog";
export { DetailGrid, DetailItem } from "./detail-grid";
export { EmptyState } from "./empty-state";
export { Grid } from "./grid";
export { InlineHeader } from "./inline-header";
export { Info } from "./info";
export type { InfoProps, InfoAccent } from "./info";
export { LinkChip } from "./link-chip";
export type { LinkChipProps, TriggerEventType } from "./link-chip";
export { ListItem } from "./list-item";
export { ListLoading } from "./list-loading";
export { MenuItem, MenuCloseContext } from "./menu-item";
export type { CloseDropdownFn } from "./menu-item";
export { MetadataGrid } from "./metadata-grid";
export type { MetadataGridProps, MetadataField } from "./metadata-grid";
export { OverflowingTextWithTooltip } from "./overflowing-text-with-tooltip";
export type { OverflowingTextWithTooltipProps } from "./overflowing-text-with-tooltip";
export { Section } from "./section";
export { Tabs, Tab, TabPanel } from "./tabs";
export { ToggleGroup, Toggle } from "./toggle-group";
export { Tag } from "./tag";
export type { TagProps, TagColor, TagVariant, TagWeight } from "./tag";
export { TintedIconTile } from "./tinted-icon-tile";
export type { TintedIconTileProps, TintedIconTileColor } from "./tinted-icon-tile";

// ── Tier 2: Widgets — modules MAY import these ───────────────────────────
export { AnimatedButton } from "./animated-button";
export type { AnimatedButtonProps } from "./animated-button";
export { AnimatedPlaceholder } from "./animated-placeholder";
export type { AnimatedPlaceholderProps, AnimatedPlaceholderType } from "./animated-placeholder";
export { Combobox } from "./combobox";
export type { ComboboxOption } from "./combobox";
export { DataTable, TextCell, TimestampCell, DurationCell, StatusCell, EditableCell } from "./data-table";
export type { SortDirection, SortState, DataTableColumn, EditableCellProps, EditableCellEditProps } from "./data-table";
export { DatePicker } from "./date-picker";
export type { DateRangePreset } from "./date-picker";
export { Dialog } from "./dialog";
export { Dropdown, useDropdownContext } from "./dropdown";
export { DropdownSearch } from "./dropdown-search";
export { ErrorBoundary } from "./error-boundary";
export { FilterBar } from "./filter-bar";
export type { ActiveFilter } from "./filter-bar";
export { FilterChips } from "./filter-chips";
export type { FilterChip } from "./filter-chips";
export { FilterDateRange } from "./filter-date-range";
export { FilterDropdown } from "./filter-dropdown";
export type { FilterField } from "./filter-dropdown";
export { Form, FormFieldInput, FormActions, FormSection, SchemaForm } from "./form";
export type { FormFieldDef } from "./form";
export { InfiniteScrollSentinel } from "./infinite-scroll-sentinel";
export { MultiSelect } from "./multi-select";
export type { MultiSelectOption } from "./multi-select";
export { Pagination } from "./pagination";
export { SearchInput } from "./search-input";
export { Select } from "./select";
export { StatCard } from "./stat-card";
export type { StatCardProps, StatCardColor, StatCardCapacity } from "./stat-card";
export { TableOptionsDropdown } from "./table-options-dropdown";
export type { ColumnOption } from "./table-options-dropdown";

// ── Tier 2: Widgets — modules MAY import these ───────────────────────────
export { Chart, BarChart, LineChart, PieChart, CalendarChart, RadarChart, HeatmapChart, StreamChart, BumpChart, ScatterPlotChart, buildNivoTheme, toSRGB, useChartTheme, chartTooltipStyle } from "./chart";
export type { ChartProps, BarDef, BarChartProps, LineDef, LineChartProps, SliceDef, PieChartProps, CalendarDay, CalendarDayStatus, CalendarChartProps, RadarDef, RadarDatum, RadarChartProps, HeatmapCell, HeatmapSerieDef, HeatmapChartProps, StreamSeriesDef, StreamChartProps, BumpSerieDef, BumpChartProps, ScatterSerieDef, ScatterPlotChartProps, ChartTheme, ChartTooltipTokens } from "./chart";

// ── Tier 2: Specialized form inputs ───────────────────────────────────────
export { IpInput, isValidIpv4 } from "./ip-input";
export { PortInput, clampPort } from "./port-input";
export { IpPortInput, parseIpPort } from "./ip-port-input";
export { ExpiryPicker } from "./expiry-picker";
export type { ExpiryPreset, ExpiryValue } from "./expiry-picker";
