/*
 *  _   _                _                     
 * | |_(_)_ __ ___   ___| | _____  ___ _ __   
 * | __| | '_ ` _ \ / _ \ |/ / _ \/ _ \ '_ \  
 * | |_| | | | | | |  __/   <  __/  __/ |_) | 
 *  \__|_|_| |_| |_|\___|_|\_\___|\___| .__/  
 *                                    |_|     
 *
 * timekeep - UI Component Library
 *
 * ⚠️  AUTO-GENERATED by scripts/generate-ui-barrel.ts
 *    Do not edit directly. Run `pnpm generate-ui-barrel` to regenerate.
 *
 * Barrel file. Every component exposes its public API via its own index.ts.
 * Import like: import { Button, Card } from "@/components/ui";
 */

// ── Core ──
export { ActionGroup } from "./action-group";
export { Avatar } from "./avatar";
export { Badge } from "./badge";
export { Banner } from "./banner";
export { Breadcrumb } from "./breadcrumb";
export type { BreadcrumbSegment } from "./breadcrumb";
export { Button } from "./button";
export type { ButtonProps } from "./button";
export { Card } from "./card";
export { Chart, BarChart, LineChart, PieChart, CalendarChart, RadarChart, HeatmapChart, StreamChart, BumpChart, ScatterPlotChart, buildNivoTheme, toSRGB, useChartTheme, chartTooltipStyle, ChartTooltip } from "./chart";
export type { ChartProps, BarDef, BarChartProps, BarTooltipData, LineDef, LineChartProps, LinePointTooltipData, SliceDef, PieChartProps, PieSliceTooltipData, CalendarDay, CalendarDayStatus, CalendarChartProps, RadarDef, RadarDatum, RadarChartProps, HeatmapCell, HeatmapSerieDef, HeatmapChartProps, StreamSeriesDef, StreamChartProps, BumpSerieDef, BumpChartProps, ScatterSerieDef, ScatterPlotChartProps, ChartTheme, ChartTooltipTokens, ChartTooltipProps } from "./chart";
export { Checkbox } from "./checkbox";
export { ClickableListItem } from "./clickable-list-item";
export { Combobox } from "./combobox";
export type { ComboboxOption } from "./combobox";
export { ConfirmDialog } from "./confirm-dialog";
export { DataTable, TextCell, TimestampCell, DurationCell, StatusCell, EditableCell } from "./data-table";
export type { SortDirection, SortState, DataTableColumn, EditableCellProps, EditableCellEditProps } from "./data-table";
export { DatePicker } from "./date-picker";
export type { DateRangePreset } from "./date-picker";
export { DetailGrid, DetailItem } from "./detail-grid";
export { Dialog } from "./dialog";
export { EllipsisDisplay, TextDisplay, BooleanDisplay, DateDisplay, NumberDisplay, SelectDisplay, MultiSelectDisplay } from "./display";
export { Dropdown, useDropdownContext } from "./dropdown";
export { DropdownSearch } from "./dropdown-search";
export { EmptyState } from "./empty-state";
export { ErrorBoundary } from "./error-boundary";
export { FieldTextInput, FieldBooleanInput, FieldDateInput, FieldSelectInput, FieldMultiSelectInput, FieldNumberInput, FieldTimeInput, FieldWeekdayToggle, isNonTextWritingKey, useRegisterFieldEvents } from "./field-input";
export type { FieldTextInputProps, FieldBooleanInputProps, FieldDateInputProps, FieldSelectInputProps, FieldMultiSelectInputProps, FieldNumberInputProps, FieldTimeInputProps, FieldWeekdayToggleProps } from "./field-input";
export { FilterBar } from "./filter-bar";
export type { ActiveFilter } from "./filter-bar";
export { FilterChips } from "./filter-chips";
export type { FilterChip } from "./filter-chips";
export { FilterDateRange } from "./filter-date-range";
export { FilterDropdown } from "./filter-dropdown";
export type { FilterField } from "./filter-dropdown";
export { Form, FormActions, FormSection, FormFieldInput, SchemaForm } from "./form";
export type { FormFieldDef } from "./form";
export { Grid } from "./grid";
export { Heading } from "./heading";
export type { HeadingLevel, HeadingColor } from "./heading";
export { IconButton } from "./icon-button";
export { InfiniteScrollSentinel } from "./infinite-scroll-sentinel";
export { InlineFieldEdit } from "./inline-field-edit";
export { InlineHeader } from "./inline-header";
export { Input } from "./input";
export { LinkChip } from "./link-chip";
export type { LinkChipProps, TriggerEventType } from "./link-chip";
export { ListItem } from "./list-item";
export { ListLoading } from "./list-loading";
export { MenuItem, MenuCloseContext } from "./menu-item";
export type { CloseDropdownFn } from "./menu-item";
export { MenuSeparator } from "./menu-separator";
export { MetadataGrid } from "./metadata-grid";
export type { MetadataGridProps, MetadataField } from "./metadata-grid";
export { MultiSelect } from "./multi-select";
export type { MultiSelectOption } from "./multi-select";
export { Pagination } from "./pagination";
export { ProgressBar } from "./progress-bar";
export { ScrollWrapper } from "./scroll-wrapper";
export type { ScrollWrapperProps } from "./scroll-wrapper";
export { SearchInput } from "./search-input";
export { Section } from "./section";
export { Select } from "./select";
export { Separator } from "./separator";
export { Skeleton, SkeletonLines } from "./skeleton";
export { Spinner } from "./spinner";
export { StatCard } from "./stat-card";
export type { StatCardProps, StatCardColor, StatCardCapacity } from "./stat-card";
export { StatusDot } from "./status-dot";
export { Switch } from "./switch";
export { TableOptionsDropdown } from "./table-options-dropdown";
export type { ColumnOption } from "./table-options-dropdown";
export { Tabs, Tab, TabPanel } from "./tabs";
export { Text } from "./text";
export type { TextVariant, TextColor, TextElement } from "./text";
export { TextArea } from "./text-area";
export { TimelineTooltip } from "./timeline-tooltip";
export type { TimelineTooltipProps } from "./timeline-tooltip";
export { ToggleGroup, Toggle } from "./toggle-group";
export { Tooltip } from "./tooltip";
export { VisuallyHidden } from "./visually-hidden";

// ── Phase 3+ molecules ──
export { PageError } from "./page-error";
export { TintedIconTile } from "./tinted-icon-tile";
export type { TintedIconTileProps, TintedIconTileColor } from "./tinted-icon-tile";
export { AnimatedPlaceholder } from "./animated-placeholder";
export type { AnimatedPlaceholderProps, AnimatedPlaceholderType } from "./animated-placeholder";
export { Info } from "./info";
export type { InfoProps, InfoAccent } from "./info";
export { Tag } from "./tag";
export type { TagProps, TagColor, TagVariant, TagWeight } from "./tag";
export { AnimatedButton } from "./animated-button";
export type { AnimatedButtonProps } from "./animated-button";
export { OverflowingTextWithTooltip } from "./overflowing-text-with-tooltip";
export type { OverflowingTextWithTooltipProps } from "./overflowing-text-with-tooltip";
export { CircularProgressBar } from "./circular-progress-bar";
export type { CircularProgressBarProps } from "./circular-progress-bar";

// ── Device management molecules ──
export { Dot } from "./dot";
export { AvatarGroup } from "./avatar-group";
export type { AvatarGroupProps } from "./avatar-group";

// ── Specialized form inputs ──
export { IpInput, isValidIpv4 } from "./ip-input";
export { PortInput, clampPort } from "./port-input";
export { IpPortInput, parseIpPort } from "./ip-port-input";
export { ExpiryPicker } from "./expiry-picker";
export type { ExpiryPreset, ExpiryValue } from "./expiry-picker";
