#!/usr/bin/env tsx
/**
 * Generates the top-level `components/ui/index.ts` barrel file.
 *
 * Scans every directory under `components/ui/`, reads each component's
 * `index.ts` to extract its public exports, and produces a clean barrel
 * that re-exports everything.
 *
 * Run via `pnpm generate-ui-barrel` (from the dashboard workspace).
 *
 * To add a new UI component:
 * 1. Create `components/ui/my-component/my-component.tsx`
 * 2. Create `components/ui/my-component/index.ts` re-exporting the public API
 * 3. Run this script — the top-level barrel is auto-updated
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");
const uiDir = resolve(rootDir, "dashboard/src/components/ui");
const barrelPath = resolve(uiDir, "index.ts");

// ── ASCII art header ───────────────────────────────────────────────────────

const HEADER = `/*
 *  _   _                _                    ${" "}
 * | |_(_)_ __ ___   ___| | _____  ___ _ __  ${" "}
 * | __| | '_ \` _ \\ / _ \\ |/ / _ \\/ _ \\ '_ \\ ${" "}
 * | |_| | | | | | |  __/   <  __/  __/ |_) |${" "}
 *  \\__|_|_| |_| |_|\\___|_|\\_\\___|\\___| .__/ ${" "}
 *                                    |_|    ${" "}
 *
 * timekeep - UI Component Library
 *
 * ⚠️  AUTO-GENERATED by scripts/generate-ui-barrel.ts
 *    Do not edit directly. Run \`pnpm generate-ui-barrel\` to regenerate.
 *
 * Barrel file. Every component exposes its public API via its own index.ts.
 * Import like: import { Button, Card } from "@/components/ui";
 */`;

// ── Types ──────────────────────────────────────────────────────────────────

/** Parsed export from a component's index.ts */
interface ParsedExport {
  name: string;
  isType: boolean;
}

/** Result of parsing a component's barrel */
interface ComponentBarrel {
  dirName: string;
  values: string[];
  types: string[];
}

// ── Parser ─────────────────────────────────────────────────────────────────

/**
 * Extract the exported name from a clause like "Foo", "Foo as Bar", or "type Foo".
 * For aliases ("Foo as Bar"), returns the alias ("Bar").
 */
function extractExportName(clause: string): { name: string; isType: boolean } {
  const trimmed = clause.trim();
  let isType = false;
  let working = trimmed;

  // Handle inline `type` keyword: "type CloseDropdownFn"
  if (working.startsWith("type ")) {
    isType = true;
    working = working.slice(5).trim();
  }

  // Handle alias: "Foo as Bar" → use "Bar"
  const asMatch = working.match(/^(.+?)\s+as\s+(.+)$/);
  if (asMatch) {
    return { name: asMatch[2].trim(), isType };
  }

  return { name: working, isType };
}

/**
 * Parses exports from a component's index.ts barrel file.
 * Handles:
 *   export { Foo, Bar } from "./foo";
 *   export type { FooProps, BarType } from "./foo";
 *   export { Foo as Bar } from "./foo";          // alias
 *   export { A, type B } from "./foo";            // inline type
 *   // comment lines are skipped
 */
function parseBarrelExports(source: string): { values: string[]; types: string[] } {
  const values: string[] = [];
  const types: string[] = [];

  const lines = source
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      return trimmed && !trimmed.startsWith("//");
    });

  for (const line of lines) {
    // Match: export type { A, B } from "..."
    const typeMatch = line.match(/^export\s+type\s+\{([^}]+)\}\s+from/);
    if (typeMatch) {
      const names = typeMatch[1].split(",").map((n) => extractExportName(n));
      types.push(...names.map((n) => n.name));
      continue;
    }

    // Match: export { A, B, type C } from "..." (possibly with inline type)
    const valueMatch = line.match(/^export\s+\{([^}]+)\}\s+from/);
    if (valueMatch) {
      const clauses = valueMatch[1].split(",").map((n) => extractExportName(n));
      for (const clause of clauses) {
        if (clause.isType) {
          types.push(clause.name);
        } else {
          values.push(clause.name);
        }
      }
    }
  }

  return { values, types };
}

/**
 * Parses named exports (export function/const/class) from a standalone .tsx file.
 * Used for files that define components directly rather than being barrel files.
 */
function parseSourceExports(source: string): string[] {
  const names: string[] = [];
  const lines = source.split("\n");

  for (const line of lines) {
    // Skip comments
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("//")) continue;

    // Match: export function Foo(...)
    let match = trimmed.match(/^export\s+function\s+(\w+)/);
    if (match) { names.push(match[1]); continue; }

    // Match: export const Foo = ...
    match = trimmed.match(/^export\s+const\s+(\w+)/);
    if (match) { names.push(match[1]); continue; }

    // Match: export class Foo ...
    match = trimmed.match(/^export\s+class\s+(\w+)/);
    if (match) { names.push(match[1]); continue; }

    // Match: export { Foo } (without from — direct named export)
    match = trimmed.match(/^export\s+\{([^}]+)\}\s*;?\s*$/);
    if (match) {
      const clauseNames = match[1].split(",").map((n) => n.trim()).filter(Boolean);
      names.push(...clauseNames);
    }
  }

  return names;
}

// ── Scanner ────────────────────────────────────────────────────────────────

/**
 * Scans all top-level component directories and parses their barrel exports.
 * Also handles standalone `.tsx` files (not in a directory).
 * Sub-components (e.g. data-table/cells/) are NOT scanned — each parent
 * component is responsible for re-exporting its own sub-exports via its index.ts.
 */
function scanComponents(): ComponentBarrel[] {
  const entries = readdirSync(uiDir, { withFileTypes: true });
  const results: ComponentBarrel[] = [];

  for (const entry of entries) {
    // ── Directory-based components (preferred pattern) ──
    if (entry.isDirectory()) {
      const indexPath = resolve(uiDir, entry.name, "index.ts");

      if (!existsSync(indexPath)) {
        if (!isStoriesOnly(entry.name)) {
          console.warn(`  ⚠️  ${entry.name}/ — no index.ts, skipping`);
        }
        continue;
      }

      const source = readFileSync(indexPath, "utf-8");
      const { values, types } = parseBarrelExports(source);

      if (values.length === 0 && types.length === 0) {
        console.warn(`  ⚠️  ${entry.name}/index.ts — no exports found, skipping`);
        continue;
      }

      results.push({ dirName: entry.name, values, types });
      continue;
    }

    // ── Standalone .tsx files (legacy/historical pattern) ──
    // These should eventually be migrated to directories with index.ts
    if (entry.isFile() && entry.name.endsWith(".tsx")) {
      // Skip the top-level index.ts itself
      if (entry.name === "index.ts") continue;

      const basename = entry.name.replace(/\.tsx$/, "");
      const filePath = resolve(uiDir, entry.name);
      const source = readFileSync(filePath, "utf-8");
      const values = parseSourceExports(source);

      if (values.length === 0) continue;

      console.warn(`  ⚠️  ${entry.name} — standalone .tsx file, consider migrating to ${basename}/ directory with index.ts`);
      results.push({ dirName: basename, values, types: [] });
    }
  }

  return results;
}

// ── Generator ──────────────────────────────────────────────────────────────

/** Generates the barrel file content from scanned components. */
function generateBarrel(components: ComponentBarrel[]): string {
  const lines: string[] = [HEADER, ""];

  // Sort alphabetically
  const sorted = [...components].sort((a, b) => a.dirName.localeCompare(b.dirName));

  // Section definitions — components grouped by logical domain
  let currentSection = "";
  const sectionOrder = [
    { name: "Phase 3+ molecules", components: ["callout", "page-error", "data-boundary", "tinted-icon-tile", "animated-placeholder", "info", "pill", "tag", "animated-button", "overflowing-text-with-tooltip", "circular-progress-bar"] },
    { name: "Device management molecules", components: ["storage-gauge", "dot", "device-status-badge", "device-health-card", "activity-timeline", "timeline", "avatar-group", "calendar-month", "view-bar"] },
    { name: "Specialized form inputs", components: ["ip-input", "port-input", "ip-port-input", "expiry-picker", "permission-multiselect"] },
    { name: "Right side panel", components: ["side-panel"] },
    { name: "Schema-driven form infrastructure", components: ["schema-driven"] },
  ];

  const sectionMap = new Map<string, string>();
  for (const section of sectionOrder) {
    for (const name of section.components) {
      sectionMap.set(name, section.name);
    }
  }

  function emitSection(name: string) {
    if (currentSection === name) return;
    if (lines[lines.length - 1] !== "") lines.push("");
    lines.push(`// ── ${name} ──`);
    currentSection = name;
  }

  function emitExports(comp: ComponentBarrel) {
    const importPath = `./${comp.dirName}`;

    // Value exports
    if (comp.values.length > 0) {
      const joined = comp.values.join(", ");
      lines.push(`export { ${joined} } from "${importPath}";`);
    }

    // Type exports
    if (comp.types.length > 0) {
      const joined = comp.types.join(", ");
      lines.push(`export type { ${joined} } from "${importPath}";`);
    }
  }

  // Emit: Core first (alphabetical), then special sections in order
  const emitted = new Set<string>();

  emitSection("Core");
  for (const comp of sorted) {
    if (sectionMap.has(comp.dirName)) continue;
    emitExports(comp);
    emitted.add(comp.dirName);
  }

  // Special sections
  for (const section of sectionOrder) {
    for (const dirName of section.components) {
      const comp = sorted.find((c) => c.dirName === dirName);
      if (!comp) continue;
      emitSection(section.name);
      emitExports(comp);
      emitted.add(dirName);
    }
  }

  // Special: form-field-meta is imported from @/lib, not ./form
  const hasFormFieldMeta = sorted.some((c) => c.dirName === "form" && c.types.includes("FormSchemaDefinition"));
  if (hasFormFieldMeta) {
    if (lines[lines.length - 1] !== "") lines.push("");
    lines.push("// ── Schema-driven form infrastructure ──");
    lines.push('export type { FormSchemaDefinition, FormFieldMetaEntry, FormSectionDef } from "@/lib/form-field-meta";');
  }

  // Warn about any component directories not in a section and not emitted
  for (const comp of sorted) {
    if (!emitted.has(comp.dirName)) {
      console.warn(`  ⚠️  ${comp.dirName} — not assigned to any section, missing from output`);
    }
  }

  // Always end with a newline
  if (lines[lines.length - 1] !== "") lines.push("");

  return lines.join("\n");
}

// ── Verification ───────────────────────────────────────────────────────────

/** A directory containing only story files is documentation-only — no barrel needed. */
function isStoriesOnly(dirName: string): boolean {
  const entries = readdirSync(resolve(uiDir, dirName), { withFileTypes: true });
  const files = entries.filter((e) => e.isFile());
  return files.length > 0 && files.every((e) => /\.stories\.(tsx|ts|mdx)$/.test(e.name));
}

/** Checks that every component directory has an index.ts with exports. */
function verifyComponents(components: ComponentBarrel[]): { clean: boolean; issues: string[] } {
  const issues: string[] = [];
  const entries = readdirSync(uiDir, { withFileTypes: true });
  const dirsWithBarrel = new Set(components.map((c) => c.dirName));

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const indexPath = resolve(uiDir, entry.name, "index.ts");
    if (!existsSync(indexPath)) {
      if (!isStoriesOnly(entry.name)) {
        issues.push(`  ❌ ${entry.name}/ — missing index.ts (create a barrel file)`);
      }
      continue;
    }

    if (!dirsWithBarrel.has(entry.name)) {
      const source = readFileSync(indexPath, "utf-8");
      const { values, types } = parseBarrelExports(source);
      if (values.length === 0 && types.length === 0) {
        issues.push(`  ❌ ${entry.name}/index.ts — no exports (add export statements)`);
      }
    }
  }

  return { clean: issues.length === 0, issues };
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const mode = process.argv.includes("--check") ? "check" : "generate";

  console.log("Scanning UI components...");
  const components = scanComponents();
  console.log(`  Found ${components.length} component barrels`);

  // Always verify
  const { clean, issues } = verifyComponents(components);
  if (issues.length > 0) {
    console.log("\nBarrel integrity issues:");
    for (const issue of issues) console.log(issue);
  }

  if (mode === "check") {
    // Check that the current barrel matches what we'd generate
    const generated = generateBarrel(components);
    const existing = readFileSync(barrelPath, "utf-8");

    // Normalize both for comparison (strip the auto-generated header line)
    const normalize = (s: string) =>
      s
        .replace(/\/\*[\s\S]*?\*\//, "") // Remove header comment
        .replace(/\/\/.*$/gm, "")         // Remove single-line comments
        .replace(/\n{3,}/g, "\n\n")       // Normalize blank lines
        .trim();

    if (normalize(generated) !== normalize(existing)) {
      console.log("\n❌ Barrel file is out of date. Run: pnpm generate-ui-barrel");
      process.exit(1);
    }
    console.log("\n✅ Barrel file is up to date.");
    return;
  }

  // Generate
  const barrel = generateBarrel(components);
  writeFileSync(barrelPath, barrel);
  console.log(`\n✅ Generated ${relative(rootDir, barrelPath)} (${components.length} components)`);

  if (issues.length > 0) {
    console.log("\n⚠️  Some components need barrel files. See issues above.");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
