/**
 * Workflow Definition Types — the contract between capture scripts and guide generators.
 *
 * A WorkflowDefinition describes a complete user guide: audience, steps,
 * screenshots, annotation callouts, tips, and warnings. The capture script
 * executes the `action` functions to produce screenshots. The generator script
 * reads the definitions to produce Typst .typ files.
 *
 * This is the SINGLE SOURCE OF TRUTH for what a guide covers.
 *
 * Usage:
 *   // 1. Define a workflow
 *   const myWorkflow: WorkflowDefinition = { ... };
 *
 *   // 2. Register it in the capture runner
 *   // 3. Register it in the guide generator
 *   // 4. Run `make docs` — both screenshots and PDFs regenerate
 */

import type { Page } from "playwright";
import type { AnnotationTarget } from "../annotations";

// ═══════════════════════════════════════════════════════════════════════
// Core Types
// ═══════════════════════════════════════════════════════════════════════

export type Audience = "admin" | "hr" | "supervisor";

/** One screenshot in a workflow step. */
export interface StepScreenshot {
  /** Output filename (e.g. "admin-device-list-01.png"). */
  filename: string;
  /** Numbered annotation callouts drawn on the screenshot. */
  annotations: AnnotationTarget[];
  /** Optional caption below the screenshot. */
  caption?: string;
}

/** A single step in a user guide workflow. */
export interface WorkflowStep {
  /** Step heading (e.g. "Navigate to the Device List"). */
  title: string;
  /**
   * Narrative explanation of this step. Shown above the screenshot.
   * Supports markdown-like formatting: *bold*, _italic_, [link].
   */
  narrative: string;
  /**
   * Async function that navigates to the correct page and waits for
   * content to load. Receives an already-authenticated Playwright Page.
   * Called by the capture runner to set up the screenshot.
   */
  navigate: (page: Page) => Promise<void>;
  /** Screenshot configuration for this step. */
  screenshot: StepScreenshot;
  /** Optional tips shown in a highlighted info box. */
  tips?: string[];
  /** Optional warnings shown in a highlighted caution box. */
  warnings?: string[];
}

/**
 * A complete user guide workflow definition.
 *
 * One workflow = one .typ output file = one PDF.
 * Steps are executed sequentially by the capture runner.
 */
export interface WorkflowDefinition {
  /** Stable identifier (e.g. "admin-device-lifecycle"). */
  id: string;
  /** Target audience role. */
  audience: Audience;
  /** Guide title (shown on cover page). */
  title: string;
  /** Short description (shown on cover page and in overview). */
  description: string;
  /** Guide version (semver). */
  version: string;
  /**
   * Username for the seed data user to log in as.
   * Must match the credentials generated by the seed binary or seed SQL.
   */
  credentials: { username: string; password: string };
  /** Overview paragraph shown after the table of contents. */
  overview: string;
  /** Prerequisites section (markdown-like). Shown before steps. */
  prerequisites?: string;
  /** Ordered workflow steps. */
  steps: WorkflowStep[];
  /** Troubleshooting section. Optional. */
  troubleshooting?: string;
  /** Related guide IDs for cross-referencing. */
  relatedGuides?: string[];
}

// ═══════════════════════════════════════════════════════════════════════
// Typst Generator Types (used by generate-guide.ts — future)
// ═══════════════════════════════════════════════════════════════════════

/** Typst callout entry — maps annotation number to description. */
export interface TypstCallout {
  number: number;
  desc: string; // Markdown-like, rendered in Typst
}

/** Typst screenshot block. */
export interface TypstScreenshot {
  filename: string;
  caption?: string;
  callouts: TypstCallout[];
}

/** Typst step block. */
export interface TypstStep {
  title: string;
  narrative: string;
  screenshot: TypstScreenshot;
  tips?: string[];
  warnings?: string[];
}

/** Full guide rendered for Typst compilation. */
export interface TypstGuide {
  title: string;
  audience: string;
  version: string;
  overview: string;
  prerequisites?: string;
  screenshotPrefix: string; // relative path to screenshots/
  steps: TypstStep[];
  troubleshooting?: string;
  relatedGuides?: string[];
}

// ═══════════════════════════════════════════════════════════════════════
// Registry (all defined workflows)
// ═══════════════════════════════════════════════════════════════════════

/** All registered workflow definitions. */
export const workflowRegistry: WorkflowDefinition[] = [];

/**
 * Register a workflow definition.
 * Called at module load time by each workflow/*.ts file.
 */
export function registerWorkflow(wf: WorkflowDefinition): void {
  // Prevent duplicate IDs
  if (workflowRegistry.some((w) => w.id === wf.id)) {
    throw new Error(`Duplicate workflow ID: ${wf.id}`);
  }
  workflowRegistry.push(wf);
}
